name: Deploy Static Website

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # giống rules của GitLab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show build info
        run: |
          echo "Building project..."
          date

      - name: Check files
        run: |
          test -f public/index.html
          test -f public/styles.css
          test -f public/js/main.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public